import { Product, CategoryInfo } from '../types/product.types';
import { Crop, CropDisease, DiseaseRecommendation, FarmerScanHistory } from '../types/recommendation.types';
import { Order } from '../types/order.types';
import { VendorInventoryItem, InventoryTransaction } from '../types/inventory.types';
import { User } from '../types/auth.types';
import { VendorProfileChangeRequest, AuditLog } from '../types/user.types';

export const MOCK_CATEGORIES: CategoryInfo[] = [
  {
    id: 'cat-1',
    name: 'Fertilizers',
    slug: 'fertilizers',
    description: 'NPK blends, water-soluble fertilizers, micronutrients, and soil health boosters.',
    iconName: 'Sprout',
    imageUrl: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80',
    productCount: 24,
    popularBrands: ['IFFCO', 'Tata Chemicals', 'Coromandel', 'Yara'],
  },
  {
    id: 'cat-2',
    name: 'Fungicides',
    slug: 'fungicides',
    description: 'Systemic and contact fungicides to eliminate blights, rots, mildew, and rust.',
    iconName: 'ShieldAlert',
    imageUrl: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=600&q=80',
    productCount: 18,
    popularBrands: ['Bayer CropScience', 'Syngenta', 'Dhanuka', 'Tata Rallis'],
  },
  {
    id: 'cat-3',
    name: 'Pesticides',
    slug: 'pesticides',
    description: 'Targeted insecticides protecting crops against bollworms, aphids, thrips, and borers.',
    iconName: 'Bug',
    imageUrl: 'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=600&q=80',
    productCount: 31,
    popularBrands: ['FMC', 'Bayer', 'PI Industries', 'UPL'],
  },
  {
    id: 'cat-4',
    name: 'Herbicides',
    slug: 'herbicides',
    description: 'Pre-emergence and post-emergence weed controls for maximum crop yield.',
    iconName: 'Scissors',
    imageUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80',
    productCount: 15,
    popularBrands: ['UPL', 'Dhanuka', 'Syngenta', 'Gharda'],
  },
  {
    id: 'cat-5',
    name: 'Seeds',
    slug: 'seeds',
    description: 'High-yielding certified hybrid and organic seeds resistant to regional pests.',
    iconName: 'Wheat',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    productCount: 28,
    popularBrands: ['Mahyco', 'Rasi Seeds', 'Kaveri Seeds', 'Advanta'],
  },
  {
    id: 'cat-6',
    name: 'Bio Products',
    slug: 'bio-products',
    description: 'Certified organic bio-fungicides, bio-stimulants, Trichoderma, and mycorrhiza.',
    iconName: 'Leaf',
    imageUrl: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=600&q=80',
    productCount: 20,
    popularBrands: ['AgriBioTech', 'Multiplex', 'Kay Bee Bio', 'Utkarsh'],
  },
  {
    id: 'cat-7',
    name: 'Crop Protection',
    slug: 'crop-protection',
    description: 'Pheromone traps, sticky sheets, sprayers, protective gear, and plant tonics.',
    iconName: 'ShieldCheck',
    imageUrl: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=600&q=80',
    productCount: 16,
    popularBrands: ['PCI Traps', 'Aspee', 'Kisan Kraft', 'GreenProtect'],
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-101',
    name: 'Bayer Nativo 75 WG Fungicide',
    brand: 'Bayer CropScience',
    category: 'Fungicides',
    sku: 'BAY-NAT-75WG-250',
    description: 'Bayer Nativo is a systemic broad-spectrum fungicide containing Tebuconazole 50% + Trifloxystrobin 25% w/w WG. It provides excellent control against Early Blight, Late Blight, Sheath Blight, Powdery Mildew, and Anthracnose. It exhibits a distinct physiological effect that improves grain quality, glossy appearance, and yield.',
    shortDescription: 'Tebuconazole 50% + Trifloxystrobin 25% WG. Premium curative and protective fungicide.',
    price: 1850,
    originalPrice: 2200,
    discountPercentage: 16,
    images: [
      'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
    packSize: '250 g',
    form: 'Granules',
    inStock: true,
    stockQuantity: 145,
    status: 'active',
    rating: 4.8,
    reviewCount: 128,
    isOrganic: false,
    recommendedForDiseases: ['dis-tom-01', 'dis-pot-01', 'dis-pad-01'], // Tomato Early Blight, Potato Late Blight, Paddy Blast
    specifications: {
      technicalName: 'Tebuconazole 50% + Trifloxystrobin 25% WG',
      chemicalFormula: 'C16H22ClN3O + C20H19F3N2O4',
      formulation: 'Water Dispersible Granules (WG)',
      dosagePerAcre: '120 - 150 g in 200 Litres water',
      dosagePerLiter: '0.6 g - 0.75 g / Litre water',
      targetCrops: ['Tomato', 'Potato', 'Paddy/Rice', 'Chilli', 'Mango', 'Grapes'],
      targetPestsAndDiseases: ['Early Blight', 'Late Blight', 'Sheath Blight', 'Blast', 'Powdery Mildew'],
      applicationMethod: 'Foliar Spray at first onset of disease symptoms',
      waitingPeriodDays: 15,
      toxicityClass: 'Blue (Moderate)',
      manufacturer: 'Bayer CropScience India Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 24,
    },
    benefits: [
      'Dual active ingredients prevent pathogen resistance',
      'Demonstrated greening effect and enhanced photosynthesis',
      'Rain-fast within 2 hours of foliar application',
      'Quick systemic uptake for both preventive and curative action'
    ],
    usageInstructions: [
      'Mix recommended 0.6g per 1 Litre of clean water in a knapsack or power sprayer.',
      'Spray during early morning or late afternoon to maximize absorption.',
      'Ensure complete coverage on both upper and lower leaf surfaces.',
      'Repeat after 10-14 days if severe weather persist.'
    ],
    safetyPrecautions: [
      'Wear protective mask, nitrile gloves, and eye goggles during mixing.',
      'Keep away from direct sunlight, food grains, and child reach.',
      'Do not spray against the wind direction.'
    ],
    vendorId: 'ven-1',
    vendorName: 'AgroTech Solutions Indore',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-08-20T14:30:00Z'
  },
  {
    id: 'prod-102',
    name: 'Trichoderma Viride 1.5% WP Bio-Fungicide',
    brand: 'Multiplex Bio-Tech',
    category: 'Bio Products',
    sku: 'MPX-TRI-VIR-1KG',
    description: 'Eco-friendly, certified organic biological fungicide containing beneficial antagonist fungus Trichoderma viride spores (2x10^6 CFU/gm). Effectively parasitizes fungal mycelium causing root rot, collar rot, damping off, and soil-borne wilt.',
    shortDescription: 'Certified organic bio-control for soil-borne & foliar fungal diseases.',
    price: 320,
    originalPrice: 400,
    discountPercentage: 20,
    images: [
      'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
    packSize: '1 Kg',
    form: 'Powder',
    inStock: true,
    stockQuantity: 210,
    status: 'active',
    rating: 4.7,
    reviewCount: 94,
    isOrganic: true,
    recommendedForDiseases: ['dis-tom-01', 'dis-chi-01', 'dis-pot-01'],
    specifications: {
      technicalName: 'Trichoderma viride 1.5% WP (CFU 2x10^6/gm min)',
      formulation: 'Wettable Powder (WP)',
      dosagePerAcre: '1.5 - 2 Kg with 100 Kg FYM / Vermicompost',
      dosagePerLiter: '5 g - 10 g / Litre for drenching/foliar',
      targetCrops: ['Tomato', 'Chilli', 'Cotton', 'Sugarcane', 'Potato', 'Pulses'],
      targetPestsAndDiseases: ['Root Rot', 'Collar Rot', 'Early Blight preventive', 'Fusarium Wilt', 'Damping Off'],
      applicationMethod: 'Seed Treatment / Soil Application / Root Drenching',
      waitingPeriodDays: 0,
      toxicityClass: 'Green (Low)',
      manufacturer: 'Multiplex Agricare Specialties',
      countryOfOrigin: 'India',
      shelfLifeMonths: 12,
    },
    benefits: [
      '100% Bio-organic and safe for beneficial soil microorganisms and pollinators',
      'Produces natural antifungal enzymes (chitinase, beta-glucanase)',
      'Enhances root proliferation and soil nutrient solubilization'
    ],
    usageInstructions: [
      'Soil application: Mix 2 kg Trichoderma in 100 kg compost/FYM, incubate under shade for 7 days before soil incorporation.',
      'Seed Treatment: 10g per 1kg seeds before sowing.'
    ],
    safetyPrecautions: [
      'Do not mix with chemical fungicides or weedicides simultaneously.',
      'Store in cool, dry place away from direct heat.'
    ],
    vendorId: 'ven-1',
    vendorName: 'AgroTech Solutions Indore',
    createdAt: '2026-01-15T11:00:00Z',
    updatedAt: '2026-08-21T09:15:00Z'
  },
  {
    id: 'prod-103',
    name: 'IFFCO 19:19:19 NPK 100% Water Soluble Fertilizer',
    brand: 'IFFCO',
    category: 'Fertilizers',
    sku: 'IFF-NPK-191919-1KG',
    description: 'Balanced water-soluble fertilizer providing equal proportions of Nitrogen, Phosphorus, and Potassium. Rapidly absorbed via foliage or drip irrigation, supplying vital macronutrients for vigorous vegetative growth, root strengthening, and disease resilience.',
    shortDescription: 'Balanced 19:19:19 NPK for rapid nutrient recovery and crop stamina.',
    price: 210,
    originalPrice: 260,
    discountPercentage: 19,
    images: [
      'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=800&q=80',
    packSize: '1 Kg',
    form: 'Soluble Powder',
    inStock: true,
    stockQuantity: 450,
    status: 'active',
    rating: 4.9,
    reviewCount: 310,
    isOrganic: false,
    recommendedForDiseases: ['dis-tom-01', 'dis-pad-01', 'dis-cot-01'],
    specifications: {
      technicalName: 'NPK 19:19:19 Water Soluble Complex',
      formulation: 'Free Flowing Crystalline Powder',
      dosagePerAcre: '3 - 5 Kg via Drip or 1 Kg / 200 L Foliar',
      dosagePerLiter: '5 g / Litre water',
      targetCrops: ['All Field, Horticultural & Vegetable Crops'],
      targetPestsAndDiseases: ['Nutrient Deficiency', 'Post-Disease Stress Recovery'],
      applicationMethod: 'Foliar Spray or Fertigation (Drip)',
      waitingPeriodDays: 0,
      toxicityClass: 'Green (Low)',
      manufacturer: 'Indian Farmers Fertiliser Cooperative Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 36,
    },
    benefits: [
      'Complete macro-nutrient balance aids rapid cell repair after pest/disease attacks',
      '100% water soluble leaving zero residue in spray nozzles',
      'Enhances chlorophyll content, flower retention, and fruit sizing'
    ],
    usageInstructions: [
      'Dissolve 5g in 1 Litre of water and spray during vegetative and early flowering stages.',
      'For drip irrigation, apply 3 kg per acre every 7-10 days.'
    ],
    safetyPrecautions: [
      'Seal pack after opening to prevent moisture clumping.',
      'Do not apply during harsh mid-day sun.'
    ],
    vendorId: 'ven-2',
    vendorName: 'Kisan Krishi Seva Kendra Nagpur',
    createdAt: '2026-02-01T08:30:00Z',
    updatedAt: '2026-08-22T10:00:00Z'
  },
  {
    id: 'prod-104',
    name: 'FMC Coragen Insecticide (Rynaxypyr)',
    brand: 'FMC India',
    category: 'Pesticides',
    sku: 'FMC-COR-150ML',
    description: 'FMC Coragen containing Rynaxypyr (Chlorantraniliprole 18.5% w/w SC) offers industry-leading protection against devastating lepidopteran pests like Pink Bollworm, Fruit Borer, Stem Borer, and Diamondback Moth. Features unique ovi-larvicidal and larvicidal activity with long residual protection.',
    shortDescription: 'Chlorantraniliprole 18.5% SC. Gold standard control for Pink Bollworm & Borers.',
    price: 1980,
    originalPrice: 2350,
    discountPercentage: 15,
    images: [
      'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=800&q=80',
    packSize: '150 ml',
    form: 'Liquid',
    inStock: true,
    stockQuantity: 88,
    status: 'active',
    rating: 4.9,
    reviewCount: 220,
    isOrganic: false,
    recommendedForDiseases: ['dis-cot-01', 'dis-tom-02'], // Cotton Pink Bollworm, Tomato Fruit Borer
    specifications: {
      technicalName: 'Chlorantraniliprole 18.5% w/w SC',
      formulation: 'Suspension Concentrate (SC)',
      dosagePerAcre: '60 ml in 200 Litres water',
      dosagePerLiter: '0.3 ml / Litre water',
      targetCrops: ['Cotton', 'Paddy', 'Tomato', 'Sugarcane', 'Soybean', 'Chilli'],
      targetPestsAndDiseases: ['Pink Bollworm', 'Spotted Bollworm', 'Fruit Borer', 'Stem Borer', 'Leaf Folder'],
      applicationMethod: 'Foliar Spray at early larval emergence',
      waitingPeriodDays: 14,
      toxicityClass: 'Green (Low)',
      manufacturer: 'FMC India Pvt. Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 24,
    },
    benefits: [
      'Stops pest feeding within minutes of ingestion',
      'Provides extended 21-day residual defense against multiple larval instars',
      'Low toxicity profile safe for beneficial insects and predators'
    ],
    usageInstructions: [
      'Mix 0.3ml per Litre of water (60ml per acre).',
      'Ensure uniform foliar coverage on fruiting bodies and bolls.'
    ],
    safetyPrecautions: [
      'Do not swallow or inhale mist.',
      'Wear protective apron and mask during spray operations.'
    ],
    vendorId: 'ven-1',
    vendorName: 'AgroTech Solutions Indore',
    createdAt: '2026-02-10T12:00:00Z',
    updatedAt: '2026-08-19T16:00:00Z'
  },
  {
    id: 'prod-105',
    name: 'Syngenta Amistar Top Fungicide',
    brand: 'Syngenta',
    category: 'Fungicides',
    sku: 'SYN-AMI-TOP-200ML',
    description: 'Syngenta Amistar Top combines Azoxystrobin (18.2%) + Difenoconazole (11.4%) SC. Provides broad-spectrum systemic protection against Paddy Blast, Sheath Blight, Chilli Anthracnose/Dieback, and Yellow Rust in Wheat.',
    shortDescription: 'Azoxystrobin 18.2% + Difenoconazole 11.4% SC for Blast and Anthracnose.',
    price: 1650,
    originalPrice: 1950,
    discountPercentage: 15,
    images: [
      'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
    packSize: '200 ml',
    form: 'Liquid',
    inStock: true,
    stockQuantity: 62,
    status: 'active',
    rating: 4.8,
    reviewCount: 89,
    isOrganic: false,
    recommendedForDiseases: ['dis-pad-01', 'dis-chi-01', 'dis-whe-01'],
    specifications: {
      technicalName: 'Azoxystrobin 18.2% + Difenoconazole 11.4% SC',
      formulation: 'Suspension Concentrate (SC)',
      dosagePerAcre: '200 ml in 200 Litres water',
      dosagePerLiter: '1 ml / Litre water',
      targetCrops: ['Paddy', 'Chilli', 'Wheat', 'Tomato', 'Maize', 'Onion'],
      targetPestsAndDiseases: ['Paddy Blast', 'Sheath Blight', 'Leaf Spot', 'Powdery Mildew', 'Yellow Rust'],
      applicationMethod: 'Foliar Spray at boot leaf stage or disease warning',
      waitingPeriodDays: 21,
      toxicityClass: 'Blue (Moderate)',
      manufacturer: 'Syngenta India Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 24,
    },
    benefits: [
      'Dual mode of action with translaminar & acropetal movement',
      'Increases crop photosynthesis and grain filling density',
      'Provides high rainfastness within 1 hour'
    ],
    usageInstructions: [
      'Dilute 1 ml in 1 Litre water.',
      'Spray thoroughly on foliage, panicles, and stem joints.'
    ],
    safetyPrecautions: [
      'Keep away from aquatic environments.',
      'Use proper protective equipment.'
    ],
    vendorId: 'ven-2',
    vendorName: 'Kisan Krishi Seva Kendra Nagpur',
    createdAt: '2026-02-15T14:00:00Z',
    updatedAt: '2026-08-20T11:45:00Z'
  },
  {
    id: 'prod-106',
    name: 'Bayer Confidor Super (Imidacloprid 30.5% SC)',
    brand: 'Bayer CropScience',
    category: 'Pesticides',
    sku: 'BAY-CON-SUP-100ML',
    description: 'Bayer Confidor Super (Imidacloprid 30.5% SC) is a world-renowned systemic neonicotinoid insecticide. Specifically tailored to combat sucking pests including Thrips, Whiteflies, Jassids, and Aphids which are the primary vectors of Leaf Curl Virus.',
    shortDescription: 'Imidacloprid 30.5% SC. Powerful systemic control for sucking pests & vector insects.',
    price: 890,
    originalPrice: 1050,
    discountPercentage: 15,
    images: [
      'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=800&q=80',
    packSize: '100 ml',
    form: 'Liquid',
    inStock: true,
    stockQuantity: 120,
    status: 'active',
    rating: 4.7,
    reviewCount: 165,
    isOrganic: false,
    recommendedForDiseases: ['dis-chi-02', 'dis-cot-02'], // Chilli Leaf Curl Vector, Cotton Whitefly
    specifications: {
      technicalName: 'Imidacloprid 30.5% SC',
      formulation: 'Suspension Concentrate (SC)',
      dosagePerAcre: '60 - 75 ml in 200 Litres water',
      dosagePerLiter: '0.3 - 0.4 ml / Litre water',
      targetCrops: ['Chilli', 'Cotton', 'Tomato', 'Paddy', 'Okra', 'Brinjal'],
      targetPestsAndDiseases: ['Thrips', 'Whiteflies', 'Aphids', 'Jassids', 'Brown Plant Hopper'],
      applicationMethod: 'Foliar Spray at early nymph/adult detection',
      waitingPeriodDays: 21,
      toxicityClass: 'Yellow (High)',
      manufacturer: 'Bayer CropScience India Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 24,
    },
    benefits: [
      'Halts virus transmission by neutralizing vector whiteflies and thrips',
      'Systemic action protects newly formed foliage and shoots',
      'Low application volume makes it economical per acre'
    ],
    usageInstructions: [
      'Mix 0.3 ml per Litre of water and spray with fine mist cone nozzle.',
      'Target underside of leaves where sucking pests colonize.'
    ],
    safetyPrecautions: [
      'Do not apply during active honeybee foraging hours.',
      'Store in original container in locked storage.'
    ],
    vendorId: 'ven-1',
    vendorName: 'AgroTech Solutions Indore',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-08-23T15:00:00Z'
  },
  {
    id: 'prod-107',
    name: 'PCI Pink Bollworm Pheromone Trap Kit (5 Traps + Lures)',
    brand: 'PCI Traps',
    category: 'Crop Protection',
    sku: 'PCI-PBW-TRAP-5PK',
    description: 'Pest Control India (PCI) specialized Pheromone Trap Kit specifically designed for monitoring and mass trapping of male Pink Bollworm (Pectinophora gossypiella) moths in cotton fields. Non-toxic, pesticide-free, certified organic practice.',
    shortDescription: 'Specialized funnel traps with Gossyplure lures for organic Pink Bollworm control.',
    price: 550,
    originalPrice: 700,
    discountPercentage: 21,
    images: [
      'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80',
    packSize: '5 Traps + 5 Lures',
    form: 'Seeds Pack',
    inStock: true,
    stockQuantity: 95,
    status: 'active',
    rating: 4.8,
    reviewCount: 77,
    isOrganic: true,
    recommendedForDiseases: ['dis-cot-01'],
    specifications: {
      technicalName: 'Gossyplure Pheromone Lures + Funnel Traps',
      formulation: 'Dispensers / Polyethylene Lures',
      dosagePerAcre: '5 Traps per Acre for monitoring, 12 for mass trapping',
      dosagePerLiter: 'N/A (Mechanical Trap)',
      targetCrops: ['Cotton', 'Okra'],
      targetPestsAndDiseases: ['Pink Bollworm', 'Spotted Bollworm'],
      applicationMethod: 'Field Installation on bamboo stakes at canopy height',
      waitingPeriodDays: 0,
      toxicityClass: 'Green (Low)',
      manufacturer: 'Pest Control (India) Pvt. Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 12,
    },
    benefits: [
      'Disrupts mating cycle, cutting next generation caterpillar population by 70%',
      'Gives precise early warning for chemical intervention thresholds',
      'Zero residue, safe for organic certification export cotton'
    ],
    usageInstructions: [
      'Install traps 45 days after sowing on stakes 1 foot above crop canopy.',
      'Replace lures every 30-40 days for continuous attraction.'
    ],
    safetyPrecautions: [
      'Handle lures with gloves to prevent scent contamination.'
    ],
    vendorId: 'ven-2',
    vendorName: 'Kisan Krishi Seva Kendra Nagpur',
    createdAt: '2026-03-05T10:30:00Z',
    updatedAt: '2026-08-20T12:00:00Z'
  },
  {
    id: 'prod-108',
    name: 'Utkarsh Micro-Nutrient Chelated Bio-Stimulant',
    brand: 'Utkarsh Agrochem',
    category: 'Bio Products',
    sku: 'UTK-CHEL-MN-500G',
    description: 'Chelated micronutrient complex (EDTA Zinc, Iron, Boron, Copper, Manganese, Molybdenum) with Ascophyllum Nodosum seaweed extract. Stimulates natural phytoalexin defense compounds to overcome viral and fungal disease stresses.',
    shortDescription: '100% Chelated multi-micronutrient + bio-stimulant for stress recovery.',
    price: 480,
    originalPrice: 600,
    discountPercentage: 20,
    images: [
      'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
    packSize: '500 g',
    form: 'Powder',
    inStock: true,
    stockQuantity: 180,
    status: 'active',
    rating: 4.9,
    reviewCount: 112,
    isOrganic: true,
    recommendedForDiseases: ['dis-chi-02', 'dis-tom-01', 'dis-whe-01'],
    specifications: {
      technicalName: 'Chelated Multi-Micronutrient + Seaweed Extract (Grade IV/II)',
      formulation: 'Soluble Micro-Granules',
      dosagePerAcre: '250 - 500 g per Acre in 200 L water',
      dosagePerLiter: '1.5 g - 2 g / Litre water',
      targetCrops: ['All Vegetable, Fruit & Cash Crops'],
      targetPestsAndDiseases: ['Yellowing (Chlorosis)', 'Viral Stunting', 'Nutrient Lock-up'],
      applicationMethod: 'Foliar spray during active vegetative flush',
      waitingPeriodDays: 0,
      toxicityClass: 'Green (Low)',
      manufacturer: 'Utkarsh Agrochem Pvt. Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 36,
    },
    benefits: [
      'Quick reversal of leaf curling, interveinal chlorosis, and stunted terminals',
      'EDTA chelation allows 100% absorption without soil locking',
      'Compatible with most organic and chemical crop protection sprays'
    ],
    usageInstructions: [
      'Mix 1.5g to 2g per Litre water and spray at early vegetative or recovery stage.'
    ],
    safetyPrecautions: [
      'Do not overdose on tender seedlings.'
    ],
    vendorId: 'ven-1',
    vendorName: 'AgroTech Solutions Indore',
    createdAt: '2026-03-10T11:00:00Z',
    updatedAt: '2026-08-22T13:00:00Z'
  },
  {
    id: 'prod-109',
    name: 'Mahyco Hybrid Tomato Seeds (Abhinav F1)',
    brand: 'Mahyco',
    category: 'Seeds',
    sku: 'MAH-TOM-ABH-10G',
    description: 'High-yielding determinate tomato hybrid seeds with built-in genetic tolerance to Tomato Leaf Curl Virus (ToLCV) and Bacterial Wilt. Produces uniform, square-round firm fruits with excellent deep red color and superior transit shelf life.',
    shortDescription: 'High yield F1 hybrid seeds with genetic tolerance to ToLCV & Bacterial Wilt.',
    price: 740,
    originalPrice: 850,
    discountPercentage: 13,
    images: [
      'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
    packSize: '10 g (approx. 3000 seeds)',
    form: 'Seeds Pack',
    inStock: true,
    stockQuantity: 150,
    status: 'active',
    rating: 4.9,
    reviewCount: 140,
    isOrganic: false,
    specifications: {
      technicalName: 'Solanum lycopersicum F1 Hybrid (Abhinav)',
      formulation: 'Treated Seeds with Thiram (3g/kg)',
      dosagePerAcre: '40 - 50 g seeds per Acre for nursery transplantation',
      dosagePerLiter: 'N/A',
      targetCrops: ['Tomato'],
      targetPestsAndDiseases: ['ToLCV Virus Tolerance', 'Bacterial Wilt Resistance'],
      applicationMethod: 'Nursery bed sowing and 25-day seedling transplantation',
      waitingPeriodDays: 60,
      toxicityClass: 'Green (Low)',
      manufacturer: 'Maharashtra Hybrid Seeds Company Pvt. Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 12,
    },
    benefits: [
      'High average yield of 35-45 Tons per acre under good management',
      'Firm fruits ideal for long distance transport without bruising',
      'Prolonged picking period (6-8 flushes)'
    ],
    usageInstructions: [
      'Raise nursery in pro-trays with coco-peat or raised nursery beds.',
      'Transplant 25-28 day old seedlings at 3 x 1.5 ft spacing.'
    ],
    safetyPrecautions: [
      'Seeds are treated with fungicide; do not consume or feed to livestock.'
    ],
    vendorId: 'ven-2',
    vendorName: 'Kisan Krishi Seva Kendra Nagpur',
    createdAt: '2026-03-12T14:30:00Z',
    updatedAt: '2026-08-18T10:00:00Z'
  },
  {
    id: 'prod-110',
    name: 'Dhanuka Dhanutop 30% EC Herbicide (Pendimethalin)',
    brand: 'Dhanuka Agritech',
    category: 'Herbicides',
    sku: 'DHA-TOP-30EC-1L',
    description: 'Dhanuka Dhanutop contains Pendimethalin 30% EC. It is an effective pre-emergence selective herbicide that controls a wide array of annual grasses and broadleaved weeds in Soybean, Cotton, Wheat, Onion, and Groundnut.',
    shortDescription: 'Pendimethalin 30% EC selective pre-emergence weed controller.',
    price: 580,
    originalPrice: 690,
    discountPercentage: 16,
    images: [
      'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80',
    packSize: '1 Litre',
    form: 'Liquid',
    inStock: true,
    stockQuantity: 110,
    status: 'active',
    rating: 4.6,
    reviewCount: 52,
    isOrganic: false,
    specifications: {
      technicalName: 'Pendimethalin 30% EC',
      chemicalFormula: 'C13H19N3O4',
      formulation: 'Emulsifiable Concentrate (EC)',
      dosagePerAcre: '1.0 - 1.25 Litres in 200 Litres water',
      dosagePerLiter: '5 ml - 6 ml / Litre water',
      targetCrops: ['Soybean', 'Cotton', 'Wheat', 'Onion', 'Garlic', 'Chilli'],
      targetPestsAndDiseases: ['Echinochloa', 'Digitaria', 'Eleusine', 'Amaranthus', 'Chenopodium'],
      applicationMethod: 'Pre-emergence soil spray within 48 hours of sowing',
      waitingPeriodDays: 60,
      toxicityClass: 'Blue (Moderate)',
      manufacturer: 'Dhanuka Agritech Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 24,
    },
    benefits: [
      'Forms a protective chemical barrier in top 2 cm soil preventing weed germination',
      'Allows young crop seedlings to establish weed-free during critical first 30 days'
    ],
    usageInstructions: [
      'Spray uniformly on moist soil within 24-48 hours of seed sowing before weed emergence.',
      'Use flat fan or floodjet nozzle.'
    ],
    safetyPrecautions: [
      'Do not disturb soil surface after spraying.'
    ],
    vendorId: 'ven-1',
    vendorName: 'AgroTech Solutions Indore',
    createdAt: '2026-03-15T09:00:00Z',
    updatedAt: '2026-08-20T17:00:00Z'
  },
  {
    id: 'prod-111',
    name: 'Tata Rallis Contaf Plus Fungicide (Hexaconazole 5% SC)',
    brand: 'Tata Rallis',
    category: 'Fungicides',
    sku: 'TAT-CON-5SC-1L',
    description: 'Systemic triazole fungicide with protective, curative, and eradicative action. Highly effective against Powdery Mildew, Rust, Rice Sheath Blight, and Tikka Leaf Spot in Groundnut.',
    shortDescription: 'Hexaconazole 5% SC systemic fungicide for Rust & Powdery Mildew.',
    price: 620,
    originalPrice: 750,
    discountPercentage: 17,
    images: [
      'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
    packSize: '1 Litre',
    form: 'Liquid',
    inStock: true,
    stockQuantity: 130,
    status: 'active',
    rating: 4.7,
    reviewCount: 98,
    isOrganic: false,
    recommendedForDiseases: ['dis-whe-01', 'dis-pad-01'],
    specifications: {
      technicalName: 'Hexaconazole 5% SC',
      formulation: 'Suspension Concentrate (SC)',
      dosagePerAcre: '400 ml in 200 Litres water',
      dosagePerLiter: '2 ml / Litre water',
      targetCrops: ['Rice/Paddy', 'Wheat', 'Groundnut', 'Mango', 'Grapes', 'Chilli'],
      targetPestsAndDiseases: ['Sheath Blight', 'Yellow Rust', 'Tikka Leaf Spot', 'Powdery Mildew'],
      applicationMethod: 'Foliar Spray',
      waitingPeriodDays: 21,
      toxicityClass: 'Blue (Moderate)',
      manufacturer: 'Rallis India Limited (A TATA Enterprise)',
      countryOfOrigin: 'India',
      shelfLifeMonths: 24,
    },
    benefits: [
      'Fast acropetal penetration into vascular system',
      'Provides phytotonic greening response and enhances grain weight'
    ],
    usageInstructions: [
      'Mix 2 ml per 1 Litre water and spray evenly over foliage.'
    ],
    safetyPrecautions: [
      'Wear protective gear during handling.'
    ],
    vendorId: 'ven-2',
    vendorName: 'Kisan Krishi Seva Kendra Nagpur',
    createdAt: '2026-03-18T10:00:00Z',
    updatedAt: '2026-08-21T11:00:00Z'
  },
  {
    id: 'prod-112',
    name: 'Bio-Shield Neem Oil 10000 PPM Azadirachtin',
    brand: 'Kay Bee Bio-Organics',
    category: 'Bio Products',
    sku: 'KBB-NEEM-10K-1L',
    description: 'Cold-pressed botanical neem extract emulsifiable concentrate with 10,000 PPM active Azadirachtin. Functions as an anti-feedant, repellent, egg-laying deterrent, and insect growth regulator (IGR) against sucking and chewing pests.',
    shortDescription: '10,000 PPM Azadirachtin organic repellent & insect growth inhibitor.',
    price: 690,
    originalPrice: 850,
    discountPercentage: 19,
    images: [
      'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
    ],
    mainImage: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
    packSize: '1 Litre',
    form: 'Liquid',
    inStock: true,
    stockQuantity: 140,
    status: 'active',
    rating: 4.8,
    reviewCount: 88,
    isOrganic: true,
    recommendedForDiseases: ['dis-chi-02', 'dis-cot-01', 'dis-tom-02'],
    specifications: {
      technicalName: 'Azadirachtin 1% (10,000 PPM) EC',
      formulation: 'Emulsifiable Concentrate (EC)',
      dosagePerAcre: '500 ml in 200 Litres water',
      dosagePerLiter: '2.5 ml - 3 ml / Litre water',
      targetCrops: ['All Vegetable, Fruit & Field Crops'],
      targetPestsAndDiseases: ['Whiteflies', 'Aphids', 'Thrips', 'Bollworm Moths', 'Mites'],
      applicationMethod: 'Foliar Spray preventive or upon pest sighting',
      waitingPeriodDays: 0,
      toxicityClass: 'Green (Low)',
      manufacturer: 'Kay Bee Bio-Organics Ltd.',
      countryOfOrigin: 'India',
      shelfLifeMonths: 24,
    },
    benefits: [
      'Zero chemical residue - harvest crops immediately with 0 day withholding',
      'Cannot develop pest resistance due to multi-mode active liminoids',
      'Certified for export organic farming by NPOP & USDA-NOP'
    ],
    usageInstructions: [
      'Mix 2.5 ml to 3 ml per Litre of clean water.',
      'Spray on both leaf sides every 10-14 days as protective cover.'
    ],
    safetyPrecautions: [
      'Shake well before mixing with water.'
    ],
    vendorId: 'ven-1',
    vendorName: 'AgroTech Solutions Indore',
    createdAt: '2026-03-20T12:00:00Z',
    updatedAt: '2026-08-22T15:00:00Z'
  }
];

export const MOCK_CROPS: Crop[] = [
  {
    id: 'crop-tom',
    name: 'Tomato',
    hindiName: 'टमाटर (Tamatar)',
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    seasons: ['Kharif', 'Rabi', 'Zaid'],
    commonDiseasesCount: 4,
  },
  {
    id: 'crop-cot',
    name: 'Cotton',
    hindiName: 'कपास (Kapas)',
    category: 'Cash Crops',
    imageUrl: 'https://images.unsplash.com/photo-1594488555823-1d011bb27163?auto=format&fit=crop&w=600&q=80',
    seasons: ['Kharif'],
    commonDiseasesCount: 3,
  },
  {
    id: 'crop-pad',
    name: 'Paddy / Rice',
    hindiName: 'धान / चावल (Dhan)',
    category: 'Cereals & Grains',
    imageUrl: 'https://images.unsplash.com/photo-1536617621972-602b9ce4a7d3?auto=format&fit=crop&w=600&q=80',
    seasons: ['Kharif', 'Rabi'],
    commonDiseasesCount: 3,
  },
  {
    id: 'crop-chi',
    name: 'Chilli',
    hindiName: 'मिर्च (Mirch)',
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
    seasons: ['Kharif', 'Rabi'],
    commonDiseasesCount: 3,
  },
  {
    id: 'crop-pot',
    name: 'Potato',
    hindiName: 'आलू (Aloo)',
    category: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    seasons: ['Rabi'],
    commonDiseasesCount: 2,
  },
  {
    id: 'crop-whe',
    name: 'Wheat',
    hindiName: 'गेहूं (Gehun)',
    category: 'Cereals & Grains',
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    seasons: ['Rabi'],
    commonDiseasesCount: 2,
  },
  {
    id: 'crop-sug',
    name: 'Sugarcane',
    hindiName: 'गन्ना (Ganna)',
    category: 'Cash Crops',
    imageUrl: 'https://images.unsplash.com/photo-1563292789-9a7f3630f9a2?auto=format&fit=crop&w=600&q=80',
    seasons: ['Kharif', 'Zaid'],
    commonDiseasesCount: 2,
  },
  {
    id: 'crop-soy',
    name: 'Soybean',
    hindiName: 'सोयाबीन (Soyabean)',
    category: 'Oilseeds',
    imageUrl: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=600&q=80',
    seasons: ['Kharif'],
    commonDiseasesCount: 2,
  }
];

export const MOCK_DISEASES: CropDisease[] = [
  {
    id: 'dis-tom-01',
    cropId: 'crop-tom',
    cropName: 'Tomato',
    name: 'Early Blight',
    hindiName: 'टमाटर का अगेती झुलसा (Ageti Jhulsa)',
    scientificName: 'Alternaria solani',
    severity: 'Severe',
    affectedParts: ['Leaves', 'Stem', 'Fruits'],
    symptoms: [
      'Dark brown to black concentric target-board rings on older lower leaves',
      'Yellow halo surrounding the dead necrotic patches',
      'Premature defoliation exposing green fruits to sunscald',
      'Dark sunken leathery lesions at stem calyx end on fruits'
    ],
    causes: [
      'High humidity (80%+) alternating with dry warm weather',
      'Overhead irrigation wetting lower foliage',
      'Fungal spores overwintering in uncomposted crop debris'
    ],
    preventiveMeasures: [
      'Maintain 3-foot bed spacing for adequate aeration',
      'Apply mulch to prevent soil-splash onto lower canopy',
      'Adopt biological seed treatment with Trichoderma viride'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'dis-cot-01',
    cropId: 'crop-cot',
    cropName: 'Cotton',
    name: 'Pink Bollworm Infestation',
    hindiName: 'कपास की गुलाबी सूंडी (Gulabi Sundi)',
    scientificName: 'Pectinophora gossypiella',
    severity: 'Critical',
    affectedParts: ['Flowers', 'Fruits'],
    symptoms: [
      'Rosetted flowers ("Gulabi phool") failing to open fully',
      'Small entry holes in green developing bolls with brown frass residue',
      'Premature opening and staining of cotton lint (locule damage)',
      'Hollowed out cotton seeds eaten by pink larvae inside bolls'
    ],
    causes: [
      'Continuous monoculture of cotton across seasons',
      'Late season warm humid weather favouring rapid moth multiplication',
      'Resistance development to first-generation Bt traits'
    ],
    preventiveMeasures: [
      'Install Gossyplure pheromone traps 45 days after sowing',
      'Adopt refuge crop planting around Bt cotton borders',
      'Destroy leftover cotton crop stalks after final picking'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1594488555823-1d011bb27163?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'dis-pad-01',
    cropId: 'crop-pad',
    cropName: 'Paddy / Rice',
    name: 'Rice Blast',
    hindiName: 'धान का झोंका रोग / ब्लास्ट (Blast Rog)',
    scientificName: 'Magnaporthe oryzae',
    severity: 'Critical',
    affectedParts: ['Leaves', 'Stem', 'Flowers'],
    symptoms: [
      'Spindle-shaped or diamond-shaped lesions with grey center and brown margins on leaves',
      'Neck Blast: Blackening and rotting of panicle node causing blank, drooping whiteheads',
      'Severe lodging and yield reduction in high nitrogen fertilized fields'
    ],
    causes: [
      'Excessive application of chemical Nitrogen/Urea without Potash balance',
      'Continuous cloudy weather with dew and temperatures between 20-26°C',
      'Dense planting obstructing airflow'
    ],
    preventiveMeasures: [
      'Balanced NPK fertilization (apply Potash in split doses)',
      'Seed soaking in bio-fungicide or carbendazim before nursery broadcasting',
      'Spray systemic fungicides at panicle emergence'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1536617621972-602b9ce4a7d3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'dis-chi-02',
    cropId: 'crop-chi',
    cropName: 'Chilli',
    name: 'Chilli Leaf Curl Virus & Vector Complex',
    hindiName: 'मिर्च का मरोड़िया रोग / चुर्रा-मुर्रा (Churra Murra)',
    scientificName: 'Chilli Leaf Curl Begomovirus / Thrips & Whitefly Vector',
    severity: 'Severe',
    affectedParts: ['Leaves', 'Stem', 'Flowers'],
    symptoms: [
      'Upward curling and boat-shaping of leaves (due to Thrips damage)',
      'Downward curling and crinkling of leaves (due to Mites & Whiteflies)',
      'Severe stunting of bushes with clustered dwarf branches ("witches broom")',
      'Flower drop and unmarketable distorted small fruits'
    ],
    causes: [
      'Heavy infestation of Bemisia tabaci (Whiteflies) transmitting the begomovirus',
      'Prolonged dry hot spells multiplying thrips populations rapidly',
      'Susceptible open-pollinated varieties'
    ],
    preventiveMeasures: [
      'Install yellow & blue sticky traps (15 per acre) early',
      'Spray systemic neonicotinoids alongside botanical neem repellent',
      'Apply chelated micronutrients and bio-stimulants to revive stunted foliage'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'dis-pot-01',
    cropId: 'crop-pot',
    cropName: 'Potato',
    name: 'Late Blight of Potato',
    hindiName: 'आलू का पछेती झुलसा (Pacheti Jhulsa)',
    scientificName: 'Phytophthora infestans',
    severity: 'Critical',
    affectedParts: ['Leaves', 'Stem', 'Roots'],
    symptoms: [
      'Water-soaked dark lesions on leaf tips that rapidly turn purplish-black',
      'White cottony fungal downy growth on underside of leaves under humid conditions',
      'Rotting and foul smell throughout the entire potato plot within 3-4 days',
      'Brown dry rot spreading into subsurface potato tubers'
    ],
    causes: [
      'Cool temperatures (12-18°C) with persistent fog or rain showers',
      'Infected seed tubers carrying latent oospores'
    ],
    preventiveMeasures: [
      'Plant certified disease-free seed tubers',
      'Prophylactic preventive spray of contact fungicide before expected cold fog waves'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'dis-whe-01',
    cropId: 'crop-whe',
    cropName: 'Wheat',
    name: 'Yellow (Stripe) Rust',
    hindiName: 'गेहूं का पीला रतुआ (Peela Ratua)',
    scientificName: 'Puccinia striiformis',
    severity: 'Severe',
    affectedParts: ['Leaves'],
    symptoms: [
      'Parallel stripes of bright yellow/orange powdery pustules on leaf blades',
      'Yellow powder stains fingers and clothes upon touch',
      'Early drying of flag leaves leading to shrivelled grain and low test weight'
    ],
    causes: [
      'Cool humid weather in North-Western plains during January-February',
      'Airborne spore dispersal from Himalayan foothills'
    ],
    preventiveMeasures: [
      'Grow resistant wheat varieties (HD-2967, PBW-550, DBW-187)',
      'Immediate spray of Triazole fungicide on first detection of yellow stripes'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
  }
];

export const MOCK_RECOMMENDATIONS: DiseaseRecommendation[] = [
  {
    id: 'rec-tom-01',
    cropId: 'crop-tom',
    cropName: 'Tomato',
    diseaseId: 'dis-tom-01',
    diseaseName: 'Early Blight',
    diseaseSeverity: 'Severe',
    advisoryNote: 'Early Blight is spreading in your tomato canopy. Apply Bayer Nativo as curative systemic spray, accompanied by NPK 19:19:19 to help damaged foliage regenerate new shoots, and Trichoderma bio-agent to sanitize soil splash.',
    isActive: true,
    updatedAt: '2026-08-20T10:00:00Z',
    recommendedProducts: [
      {
        productId: 'prod-101',
        category: 'Fungicides',
        role: 'Primary Treatment',
        priority: 1,
        reason: 'Tebuconazole + Trifloxystrobin rapidly arrests Alternaria spore germination and cures active leaf spots.',
        applicationSchedule: 'Spray 0.6g/L water early morning; repeat after 10 days if humid weather persists.',
        isActive: true,
      },
      {
        productId: 'prod-103',
        category: 'Fertilizers',
        role: 'Bio-Stimulant / Recovery',
        priority: 2,
        reason: 'Supplies balanced 19:19:19 nitrogen-potash nutrition to restore photosynthetic chlorophyll and heal cellular damage.',
        applicationSchedule: 'Mix 5g/L water along with the fungicide or spray 3 days post curative treatment.',
        isActive: true,
      },
      {
        productId: 'prod-102',
        category: 'Bio Products',
        role: 'Soil Enhancer',
        priority: 3,
        reason: 'Soil application creates a protective microbial shield around roots, preventing reinfection from soil spores.',
        applicationSchedule: 'Apply 2kg per acre mixed in well-rotted FYM/vermicompost around plant root zones.',
        isActive: true,
      }
    ]
  },
  {
    id: 'rec-cot-01',
    cropId: 'crop-cot',
    cropName: 'Cotton',
    diseaseId: 'dis-cot-01',
    diseaseName: 'Pink Bollworm Infestation',
    diseaseSeverity: 'Critical',
    advisoryNote: 'Critical pink bollworm window detected. Deploy FMC Coragen for immediate larvicidal protection, install PCI pheromone traps to disrupt adult moth mating, and spray Neem Oil botanical repellent.',
    isActive: true,
    updatedAt: '2026-08-22T14:00:00Z',
    recommendedProducts: [
      {
        productId: 'prod-104',
        category: 'Pesticides',
        role: 'Primary Treatment',
        priority: 1,
        reason: 'Chlorantraniliprole paralyzes emerging larvae before they bore into developing green bolls.',
        applicationSchedule: 'Spray 0.3 ml/L water (60 ml/acre) targeting young fruiting squares and squares.',
        isActive: true,
      },
      {
        productId: 'prod-107',
        category: 'Crop Protection',
        role: 'Preventive Foliar',
        priority: 2,
        reason: 'Pheromone lures trap male moths to prevent egg laying on bolls and monitor infestation thresholds.',
        applicationSchedule: 'Install 5-8 traps per acre 1 foot above crop canopy immediately.',
        isActive: true,
      },
      {
        productId: 'prod-112',
        category: 'Bio Products',
        role: 'Bio-Stimulant / Recovery',
        priority: 3,
        reason: 'Botanical Azadirachtin deters female moths from ovipositing eggs on tender bolls.',
        applicationSchedule: 'Spray 2.5 ml/L water 7 days after chemical spray.',
        isActive: true,
      }
    ]
  },
  {
    id: 'rec-pad-01',
    cropId: 'crop-pad',
    cropName: 'Paddy / Rice',
    diseaseId: 'dis-pad-01',
    diseaseName: 'Rice Blast',
    diseaseSeverity: 'Critical',
    advisoryNote: 'Rice Blast symptoms detected. Azoxystrobin + Difenoconazole is recommended for leaf and neck blast protection. Supplement with soluble NPK 19:19:19 to strengthen cell walls.',
    isActive: true,
    updatedAt: '2026-08-21T16:00:00Z',
    recommendedProducts: [
      {
        productId: 'prod-105',
        category: 'Fungicides',
        role: 'Primary Treatment',
        priority: 1,
        reason: 'Syngenta Amistar Top delivers translaminar systemic action protecting newly emerged boot leaves and panicle necks.',
        applicationSchedule: 'Spray 1 ml/L water (200 ml/acre) at boot leaf or early flowering stage.',
        isActive: true,
      },
      {
        productId: 'prod-111',
        category: 'Fungicides',
        role: 'Preventive Foliar',
        priority: 2,
        reason: 'Tata Contaf Plus provides economical secondary systemic triazole protection against sheath blight.',
        applicationSchedule: 'Spray 2 ml/L water if sheath rot is also observed.',
        isActive: true,
      },
      {
        productId: 'prod-103',
        category: 'Fertilizers',
        role: 'Bio-Stimulant / Recovery',
        priority: 3,
        reason: 'Promotes rapid panicle elongation and ensures full grain filling in stressed paddy fields.',
        applicationSchedule: 'Foliar spray 5g/L water.',
        isActive: true,
      }
    ]
  },
  {
    id: 'rec-chi-02',
    cropId: 'crop-chi',
    cropName: 'Chilli',
    diseaseId: 'dis-chi-02',
    diseaseName: 'Chilli Leaf Curl Virus & Vector Complex',
    diseaseSeverity: 'Severe',
    advisoryNote: 'Control vector sucking pests (thrips & whiteflies) with Confidor Super, spray Chelated Micronutrients + Bio-stimulant to trigger new healthy leaves, and apply Neem Oil deterrent.',
    isActive: true,
    updatedAt: '2026-08-23T11:00:00Z',
    recommendedProducts: [
      {
        productId: 'prod-106',
        category: 'Pesticides',
        role: 'Primary Treatment',
        priority: 1,
        reason: 'Imidacloprid 30.5% SC quickly knocks down whitefly and thrips vectors transmitting the curl virus.',
        applicationSchedule: 'Spray 0.3 ml/L water targeting lower leaf undersides.',
        isActive: true,
      },
      {
        productId: 'prod-108',
        category: 'Bio Products',
        role: 'Bio-Stimulant / Recovery',
        priority: 2,
        reason: 'Chelated zinc, boron, and seaweed stimulate terminal buds to push new uncurled green flushes.',
        applicationSchedule: 'Mix 1.5 g/L water and spray 4 days after pesticide application.',
        isActive: true,
      },
      {
        productId: 'prod-112',
        category: 'Bio Products',
        role: 'Preventive Foliar',
        priority: 3,
        reason: '10,000 PPM Neem Oil creates a repellent barrier against subsequent whitefly swarms.',
        applicationSchedule: 'Spray 3 ml/L water every 10 days.',
        isActive: true,
      }
    ]
  }
];

export const MOCK_USERS: User[] = [
  {
    id: 'usr-farmer-1',
    fullName: 'Ramesh Patel',
    email: 'ramesh.patel@kisaan.in',
    phone: '+91 98765 43210',
    role: 'farmer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    kisanId: 'KISAN-MP-2024-8841',
    createdAt: '2025-11-10T10:00:00Z',
    addresses: [
      {
        id: 'addr-1',
        name: 'Ramesh Patel (Farm House)',
        phone: '+91 98765 43210',
        alternatePhone: '+91 94250 11223',
        addressLine1: 'Survey No. 42/B, Near Gram Panchayat Tube-well',
        addressLine2: 'Semaliya Chauki Road',
        landmark: 'Behind Primary Kisan Kendra',
        villageOrCity: 'Dharampuri',
        district: 'Dhar',
        state: 'Madhya Pradesh',
        pincode: '454552',
        isDefault: true,
        addressType: 'farm',
      },
      {
        id: 'addr-2',
        name: 'Ramesh Patel (Indore Residence)',
        phone: '+91 98765 43210',
        addressLine1: 'Flat 304, Shrinath Residency, Annapurna Road',
        villageOrCity: 'Indore',
        district: 'Indore',
        state: 'Madhya Pradesh',
        pincode: '452009',
        isDefault: false,
        addressType: 'home',
      }
    ]
  },
  {
    id: 'usr-vendor-1',
    fullName: 'Suresh Verma',
    email: 'vendor.agrotech@kafaas.com',
    phone: '+91 98260 77889',
    role: 'vendor',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    vendorBusinessName: 'AgroTech Solutions Indore',
    vendorGstin: '23AABCA1234F1Z8',
    vendorLicenseNo: 'AGRI/MP/IND/2022/9041',
    vendorApprovalStatus: 'approved',
    createdAt: '2025-10-01T08:00:00Z',
    addresses: [
      {
        id: 'addr-v1',
        name: 'AgroTech Central Warehouse',
        phone: '+91 98260 77889',
        addressLine1: 'Plot 18, Sanwer Road Industrial Area, Sector B',
        villageOrCity: 'Indore',
        district: 'Indore',
        state: 'Madhya Pradesh',
        pincode: '452015',
        isDefault: true,
        addressType: 'warehouse',
      }
    ]
  },
  {
    id: 'usr-admin-1',
    fullName: 'Rajesh Sharma (Admin)',
    email: 'admin@kafaas.com',
    phone: '+91 91111 22334',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    createdAt: '2025-08-01T00:00:00Z',
    addresses: []
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-8801',
    orderNumber: 'KF-2026-08801',
    userId: 'usr-farmer-1',
    customerName: 'Ramesh Patel',
    customerPhone: '+91 98765 43210',
    customerEmail: 'ramesh.patel@kisaan.in',
    shippingAddress: {
      id: 'addr-1',
      name: 'Ramesh Patel (Farm House)',
      phone: '+91 98765 43210',
      addressLine1: 'Survey No. 42/B, Near Gram Panchayat Tube-well',
      villageOrCity: 'Dharampuri',
      district: 'Dhar',
      state: 'Madhya Pradesh',
      pincode: '454552',
      isDefault: true,
      addressType: 'farm',
    },
    items: [
      {
        id: 'item-1',
        productId: 'prod-101',
        productName: 'Bayer Nativo 75 WG Fungicide',
        brand: 'Bayer CropScience',
        category: 'Fungicides',
        image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
        packSize: '250 g',
        unitPrice: 1850,
        quantity: 2,
        totalPrice: 3700,
        sku: 'BAY-NAT-75WG-250',
        vendorId: 'usr-vendor-1',
        vendorName: 'AgroTech Solutions Indore',
      },
      {
        id: 'item-2',
        productId: 'prod-103',
        productName: 'IFFCO 19:19:19 NPK 100% Water Soluble Fertilizer',
        brand: 'IFFCO',
        category: 'Fertilizers',
        image: 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=800&q=80',
        packSize: '1 Kg',
        unitPrice: 210,
        quantity: 3,
        totalPrice: 630,
        sku: 'IFF-NPK-191919-1KG',
        vendorId: 'usr-vendor-1',
        vendorName: 'AgroTech Solutions Indore',
      }
    ],
    pricing: {
      subtotal: 4330,
      discount: 400,
      farmerSubsidyDiscount: 200,
      deliveryCharge: 0,
      taxGst: 224,
      totalAmount: 3954,
    },
    status: 'shipped',
    paymentStatus: 'paid',
    paymentMethod: 'upi',
    paymentTransactionId: 'UPI/260824009182/YESB',
    timeline: [
      {
        status: 'pending',
        title: 'Order Placed',
        description: 'Order confirmed and payment verified via UPI.',
        timestamp: '2026-08-23T11:20:00Z',
        completed: true,
      },
      {
        status: 'confirmed',
        title: 'Vendor Accepted',
        description: 'AgroTech Solutions Indore allocated inventory batch #MP-2026-B1.',
        timestamp: '2026-08-23T14:15:00Z',
        completed: true,
      },
      {
        status: 'processing',
        title: 'Packed & Quality Checked',
        description: 'Sealed agrochemical packaging passed moisture and barcode check.',
        timestamp: '2026-08-24T09:30:00Z',
        completed: true,
      },
      {
        status: 'shipped',
        title: 'Dispatched via Rural Kisan Logistics',
        description: 'Consignment tracking #RKL-IND-8910 en route to Dharampuri hub.',
        location: 'Indore Central Hub',
        timestamp: '2026-08-24T18:00:00Z',
        completed: true,
      },
      {
        status: 'out_for_delivery',
        title: 'Out for Farm Delivery',
        description: 'Rider reaching farm address with OTP confirmation.',
        timestamp: '',
        completed: false,
      },
      {
        status: 'delivered',
        title: 'Delivered to Farmer',
        description: 'Handover complete.',
        timestamp: '',
        completed: false,
      }
    ],
    cancellationAllowed: false,
    vendorId: 'usr-vendor-1',
    createdAt: '2026-08-23T11:20:00Z',
    updatedAt: '2026-08-24T18:00:00Z',
    estimatedDeliveryDate: '2026-08-26'
  },
  {
    id: 'ord-8802',
    orderNumber: 'KF-2026-08802',
    userId: 'usr-farmer-1',
    customerName: 'Ramesh Patel',
    customerPhone: '+91 98765 43210',
    customerEmail: 'ramesh.patel@kisaan.in',
    shippingAddress: {
      id: 'addr-1',
      name: 'Ramesh Patel (Farm House)',
      phone: '+91 98765 43210',
      addressLine1: 'Survey No. 42/B, Near Gram Panchayat Tube-well',
      villageOrCity: 'Dharampuri',
      district: 'Dhar',
      state: 'Madhya Pradesh',
      pincode: '454552',
      isDefault: true,
      addressType: 'farm',
    },
    items: [
      {
        id: 'item-3',
        productId: 'prod-104',
        productName: 'FMC Coragen Insecticide (Rynaxypyr)',
        brand: 'FMC India',
        category: 'Pesticides',
        image: 'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=800&q=80',
        packSize: '150 ml',
        unitPrice: 1980,
        quantity: 1,
        totalPrice: 1980,
        sku: 'FMC-COR-150ML',
        vendorId: 'usr-vendor-1',
        vendorName: 'AgroTech Solutions Indore',
      }
    ],
    pricing: {
      subtotal: 1980,
      discount: 100,
      farmerSubsidyDiscount: 100,
      deliveryCharge: 0,
      taxGst: 106,
      totalAmount: 1886,
    },
    status: 'delivered',
    paymentStatus: 'paid',
    paymentMethod: 'cod',
    paymentTransactionId: 'COD-CASH-RECVD',
    timeline: [
      {
        status: 'pending',
        title: 'Order Placed',
        description: 'Cash on Delivery order booked.',
        timestamp: '2026-08-10T10:00:00Z',
        completed: true,
      },
      {
        status: 'confirmed',
        title: 'Confirmed',
        description: 'Order confirmed by vendor.',
        timestamp: '2026-08-10T11:00:00Z',
        completed: true,
      },
      {
        status: 'processing',
        title: 'Processed',
        description: 'Item packed in weather-proof container.',
        timestamp: '2026-08-11T09:00:00Z',
        completed: true,
      },
      {
        status: 'shipped',
        title: 'Dispatched',
        description: 'In transit to Dhar hub.',
        timestamp: '2026-08-11T16:00:00Z',
        completed: true,
      },
      {
        status: 'out_for_delivery',
        title: 'Out for Delivery',
        description: 'Agent Mukesh Singh assigned.',
        timestamp: '2026-08-13T08:30:00Z',
        completed: true,
      },
      {
        status: 'delivered',
        title: 'Delivered',
        description: 'Package handed over to farmer with cash collection.',
        timestamp: '2026-08-13T14:45:00Z',
        completed: true,
      }
    ],
    cancellationAllowed: false,
    vendorId: 'usr-vendor-1',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-13T14:45:00Z',
    estimatedDeliveryDate: '2026-08-13'
  }
];

export const MOCK_SCAN_HISTORY: FarmerScanHistory[] = [
  {
    id: 'scan-001',
    scanCode: 'SCAN-TOM-2026-0819',
    cropName: 'Tomato',
    cropId: 'crop-tom',
    diseaseDetected: 'Early Blight (Alternaria solani)',
    diseaseId: 'dis-tom-01',
    confidenceScore: 96,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    scanDate: '2026-08-19T14:20:00Z',
    plotName: 'North Field Plot #2 (Tomato Hybrid)',
    status: 'Treated',
    recommendations: MOCK_RECOMMENDATIONS[0].recommendedProducts
  },
  {
    id: 'scan-002',
    scanCode: 'SCAN-COT-2026-0822',
    cropName: 'Cotton',
    cropId: 'crop-cot',
    diseaseDetected: 'Pink Bollworm Infestation',
    diseaseId: 'dis-cot-01',
    confidenceScore: 92,
    imageUrl: 'https://images.unsplash.com/photo-1594488555823-1d011bb27163?auto=format&fit=crop&w=600&q=80',
    scanDate: '2026-08-22T09:10:00Z',
    plotName: 'South Riverbed Plot #4 (Cotton Bt-II)',
    status: 'Active Issue',
    recommendations: MOCK_RECOMMENDATIONS[1].recommendedProducts
  }
];

export const MOCK_VENDOR_INVENTORY: VendorInventoryItem[] = [
  {
    id: 'inv-101',
    productId: 'prod-101',
    productName: 'Bayer Nativo 75 WG Fungicide',
    brand: 'Bayer CropScience',
    category: 'Fungicides',
    sku: 'BAY-NAT-75WG-250',
    mainImage: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=800&q=80',
    packSize: '250 g',
    price: 1850,
    availableStock: 145,
    reservedStock: 12,
    totalStock: 157,
    lowStockThreshold: 25,
    status: 'active',
    isLowStock: false,
    lastRestockedAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-24T18:00:00Z',
    warehouseLocation: 'Indore Central Shelf B-4',
  },
  {
    id: 'inv-102',
    productId: 'prod-102',
    productName: 'Trichoderma Viride 1.5% WP Bio-Fungicide',
    brand: 'Multiplex Bio-Tech',
    category: 'Bio Products',
    sku: 'MPX-TRI-VIR-1KG',
    mainImage: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
    packSize: '1 Kg',
    price: 320,
    availableStock: 210,
    reservedStock: 8,
    totalStock: 218,
    lowStockThreshold: 40,
    status: 'active',
    isLowStock: false,
    lastRestockedAt: '2026-08-10T14:00:00Z',
    updatedAt: '2026-08-22T09:00:00Z',
    warehouseLocation: 'Indore Central Shelf A-1 (Bio-Cool)',
  },
  {
    id: 'inv-104',
    productId: 'prod-104',
    productName: 'FMC Coragen Insecticide (Rynaxypyr)',
    brand: 'FMC India',
    category: 'Pesticides',
    sku: 'FMC-COR-150ML',
    mainImage: 'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=800&q=80',
    packSize: '150 ml',
    price: 1980,
    availableStock: 18,
    reservedStock: 6,
    totalStock: 24,
    lowStockThreshold: 30,
    status: 'active',
    isLowStock: true,
    lastRestockedAt: '2026-07-28T09:00:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
    warehouseLocation: 'Indore Central Safe C-2',
  },
  {
    id: 'inv-106',
    productId: 'prod-106',
    productName: 'Bayer Confidor Super (Imidacloprid 30.5% SC)',
    brand: 'Bayer CropScience',
    category: 'Pesticides',
    sku: 'BAY-CON-SUP-100ML',
    mainImage: 'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=800&q=80',
    packSize: '100 ml',
    price: 890,
    availableStock: 120,
    reservedStock: 15,
    totalStock: 135,
    lowStockThreshold: 20,
    status: 'active',
    isLowStock: false,
    lastRestockedAt: '2026-08-18T10:00:00Z',
    updatedAt: '2026-08-23T15:00:00Z',
    warehouseLocation: 'Indore Central Safe C-4',
  }
];

export const MOCK_INVENTORY_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: 'tx-901',
    productId: 'prod-101',
    productName: 'Bayer Nativo 75 WG Fungicide',
    sku: 'BAY-NAT-75WG-250',
    vendorId: 'usr-vendor-1',
    vendorName: 'AgroTech Solutions Indore',
    type: 'restock',
    quantityChange: 100,
    previousStock: 45,
    newStock: 145,
    referenceId: 'BATCH-BAY-260815',
    reason: 'Monthly replenishment received from Bayer regional depot',
    performedBy: 'Suresh Verma (Vendor)',
    performedByRole: 'vendor',
    timestamp: '2026-08-15T10:00:00Z',
  },
  {
    id: 'tx-902',
    productId: 'prod-101',
    productName: 'Bayer Nativo 75 WG Fungicide',
    sku: 'BAY-NAT-75WG-250',
    vendorId: 'usr-vendor-1',
    vendorName: 'AgroTech Solutions Indore',
    type: 'reservation',
    quantityChange: -2,
    previousStock: 145,
    newStock: 143,
    referenceId: 'ORD-KF-2026-08801',
    reason: 'Reserved for order dispatch to Ramesh Patel',
    performedBy: 'System Auto-Reserve',
    performedByRole: 'system',
    timestamp: '2026-08-23T11:20:00Z',
  },
  {
    id: 'tx-903',
    productId: 'prod-104',
    productName: 'FMC Coragen Insecticide (Rynaxypyr)',
    sku: 'FMC-COR-150ML',
    vendorId: 'usr-vendor-1',
    vendorName: 'AgroTech Solutions Indore',
    type: 'adjustment',
    quantityChange: -5,
    previousStock: 29,
    newStock: 24,
    referenceId: 'AUD-INV-2026-0824',
    reason: 'Damaged outer seal during transit pallet inspection',
    performedBy: 'Rajesh Sharma (Admin)',
    performedByRole: 'admin',
    timestamp: '2026-08-24T15:30:00Z',
  }
];

export const MOCK_VENDOR_CHANGE_REQUESTS: VendorProfileChangeRequest[] = [
  {
    id: 'vcr-001',
    vendorId: 'usr-vendor-1',
    vendorName: 'AgroTech Solutions Indore',
    currentData: {
      businessName: 'AgroTech Solutions Indore',
      contactPerson: 'Suresh Verma',
      phone: '+91 98260 77889',
      email: 'vendor.agrotech@kafaas.com',
      gstin: '23AABCA1234F1Z8',
      licenseNumber: 'AGRI/MP/IND/2022/9041',
      warehouseAddress: 'Plot 18, Sanwer Road Industrial Area, Sector B',
      state: 'Madhya Pradesh',
      district: 'Indore',
      bankAccountName: 'AgroTech Solutions Current A/C',
      bankAccountNumber: '918020038910291',
      ifscCode: 'HDFC0001024',
    },
    proposedData: {
      businessName: 'AgroTech Kisan Agro Services Pvt Ltd',
      contactPerson: 'Suresh Verma',
      phone: '+91 98260 77889',
      email: 'contact@agrotechindia.org',
      gstin: '23AABCA1234F1Z8',
      licenseNumber: 'AGRI/MP/IND/2022/9041-RENEWED',
      warehouseAddress: 'Plot 18-20, Sanwer Road Mega Logistics Park, Sector B',
      state: 'Madhya Pradesh',
      district: 'Indore',
      bankAccountName: 'AgroTech Kisan Agro Services Pvt Ltd',
      bankAccountNumber: '918020038910291',
      ifscCode: 'HDFC0001024',
    },
    reasonForChange: 'Incorporation from Sole Proprietorship to Private Limited entity and warehouse expansion.',
    status: 'pending',
    createdAt: '2026-08-24T16:00:00Z',
  }
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    actorId: 'usr-admin-1',
    actorName: 'Rajesh Sharma',
    actorRole: 'admin',
    action: 'CREATE_PRODUCT',
    targetEntity: 'product',
    targetId: 'prod-112',
    details: 'Created new organic bio-product listing: Bio-Shield Neem Oil 10000 PPM',
    ipAddress: '103.21.144.12',
    timestamp: '2026-08-20T12:00:00Z',
  },
  {
    id: 'log-002',
    actorId: 'usr-admin-1',
    actorName: 'Rajesh Sharma',
    actorRole: 'admin',
    action: 'UPDATE_RECOMMENDATION_MATRIX',
    targetEntity: 'recommendation',
    targetId: 'rec-cot-01',
    details: 'Added FMC Coragen as Priority #1 primary treatment for Cotton Pink Bollworm',
    ipAddress: '103.21.144.12',
    timestamp: '2026-08-22T14:05:00Z',
  },
  {
    id: 'log-003',
    actorId: 'usr-vendor-1',
    actorName: 'Suresh Verma',
    actorRole: 'vendor',
    action: 'SUBMIT_PROFILE_CHANGE_REQUEST',
    targetEntity: 'vendor_request',
    targetId: 'vcr-001',
    details: 'Submitted business entity name and expanded warehouse address change for admin review',
    ipAddress: '157.34.88.90',
    timestamp: '2026-08-24T16:00:00Z',
  }
];
